language: node_js
node_js:
  - "10"
install:
  - npm install -g vuepress
script:
  - cd docs
  - vuepress build
cache:
  directories:
    - "node_modules"
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN # A token generated on GitHub allowing Travis to push code on you repository. Set in the Travis settings page of your repository, as a secure variable
  repo: voilaah/oc-eclia-docs
  keep_history: true
  target-branch: master
  on:
    branch: master
